### ISSUE TITLE
ajax loading or autoreload would be pretty nice, too

### ISSUE THREAD

**Issue by deanmalmgren** [ymichael/cprofilev#21]
I'm fine reloading the page every once in a while, but for longer running things, it'd be pretty awesome to either autoreload or, better yet, update the results with an ajax request to the bottle server. I have a profiling job that might take upwards of an hour where I check back from time to time and that'd be pretty nice. If we do something like #19, this should be pretty straightforward to implement. Thoughts?

**Comment by ymichael** [comment]
Yea - Reloading every once in a while might be irritating if unintended and you end up losing state. It'd be nice to be able to have auto reloading as an option though.

**Comment by deanmalmgren** [comment]
Yeah, I can see what you mean. It would be pretty annoying to have a table that I'm studying update dynamically. I'm going to close this out.
